// Order  constant 

export const ORDER_FIND_REQUEST = "ORDER_FIND_REQUEST";
export const ORDER_FIND_SUCCESS = "ORDER_FIND_SUCCESS";
export const ORDER_FIND_ERR = "ORDER_FIND_ERR ";

// order statusChange

export const ORDER_STATUSCHANGE_REQUEST = "ORDER_STATUSCHANGE_REQUEST";
export const ORDER_STATUSCHANGE_SUCCESS = "ORDER_STATUSCHANGE_SUCCESS";
export const ORDER_STATUSCHANGE_ERR = "ORDER_STATUSCHANGE_ERR ";