//  Product create Constants

export const PRODUCT_CREATE_REQUEST = "PRODUCT_CREATE_REQUEST";
export const PRODUCT_CREATE_SUCCESS = "PRODUCT_CREATE_SUCCESS";
export const PRODUCT_CREATE_ERR = "PRODUCT_CREATE_ERR ";

//  Product find Constants

export const PRODUCT_FIND_REQUEST = "PRODUCT_FIND_REQUEST";
export const PRODUCT_FIND_SUCCESS = "PRODUCT_FIND_SUCCESS";
export const PRODUCT_FIND_ERR = "PRODUCT_FIND_ERR ";

//  Product update Constants

export const PRODUCT_UPDATE_REQUEST = "PRODUCT_UPDATE_REQUEST";
export const PRODUCT_UPDATE_SUCCESS = "PRODUCT_UPDATE_SUCCESS";
export const PRODUCT_UPDATE_ERR = "PRODUCT_UPDATE_ERR ";

//  Product statusChange Constants

export const PRODUCT_STATUSCHANGE_REQUEST = "PRODUCT_STATUSCHANGE_REQUEST";
export const PRODUCT_STATUSCHANGE_SUCCESS = "PRODUCT_STATUSCHANGE_SUCCESS";
export const PRODUCT_STATUSCHANGE_ERR = "PRODUCT_STATUSCHANGE_ERR ";
